name: Lesson 6

on:
  push:
    branches:
      - lesson-6-complete
jobs:
  function_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Run functional tests
        run: npm test -- --coverage --watchAll=false
  deploy:
    needs: [function_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
  security_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Start frontend app
        run: npm start -- --host 0.0.0.0 &
      - name: Wait for app to become available
        run: |
          n=0
          until curl --silent --fail http://localhost:3000; do
            n=$((n+1))
            if [ "$n" -ge 30 ]; then
              echo "App did not start in time"
              exit 1
            fi
            sleep 2
          done
      - name: Dynamic Application Security Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
  acceptance_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    container: cypress/included:10.3.0
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Start frontend app
        run: npm start -- --host 0.0.0.0 &
      - name: Wait for app to become available
        run: |
          n=0
          until curl --silent --fail http://localhost:3000; do
            n=$((n+1))
            if [ "$n" -ge 30 ]; then
              echo "App did not start in time"
              exit 1
            fi
            sleep 2
          done
      - name: Run Cypress acceptance tests
        run: npx cypress run --config-file=cypress.config.js --headless
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos